export enum CAR_BRANDS {
  ALL = 'ALL',
  TOYOTA = 'TOYOTA',
  NISSAN = 'NISSAN',
  AUDI = 'AUDI',
  PORSCHE = 'PORSCHE',
  MAZDA = 'MAZDA',
  MITSUBISHI = 'MITSUBISHI',
  BMW = 'BMW',
  BENZ = 'BENZ',
  HONDA = 'HONDA',
  FORD = 'FORD',
}

export enum TRANSMISSION_TYPES {
  ALL = 'ALL',
  AUTO = 'AUTO',
  MANUAL = 'MANUAL',
  CVT = 'CVT',
}

export enum FUEL_TYPE {
  DIESEL = 'DIESEL',
  PETROL = 'PETROL',
  HYBRID = 'HYBRID',
  ELECTRIC = 'ELECTRIC',
  PLUGIN_HYBRID = 'PLUGIN HYBRID',
  GASOLINE = 'GASOLINE',
  OTHER = 'OTHER',
}

export enum VEHICLE_TYPE {
  CAR = 'CAR',
  SUV = 'SUV',
  VAN = 'VAN',
  CAB = 'CAB',
  JEEP = 'JEEP',
  LORRY = 'LORRY',
  TRUCK = 'TRUCK',
  OTHER = 'OTHER',
}
